name: Deploy to PRD

on:
  push:
    # Only run workflow for pushes to specific branches
    branches:
      - main

jobs:
  balena-push:
    runs-on: ubuntu-latest
    environment: Production
    steps:
      - uses: actions/checkout@v2
      - uses: balena-io-playground/github-actions/actions/build-release@master
        id: build
        with:
          balena_token: ${{ secrets.BALENA_TOKEN }}
          application: dal-lounge-lights
      - name: Log release ID built
        run: echo "Built release ID ${{ steps.build.outputs.release_id }}"
